http://www.{default}/:
  to: http://{default}/
  type: redirect
http://{default}/:
  cache:
    cookies:
    - '*'
    default_ttl: 0
    enabled: true
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: true
  type: upstream
  upstream: php:php
